### ISSUE TITLE
[Suggestion] Mines shouldn't react to specific enemies

### ISSUE THREAD

**Issue by Diffle** [DrFeederino/AndysModsPlugin#1]
You can argue about the blob, coli-head and nutcracker, but they definitely should not react to ghost girl, because...Well, she's a ghost. And that doesn't make any sense.

**Comment by Diffle** [comment]
About nutcracker: he's kind of guardian of the facility, so that's a bit odd too, same applies to the coild-head. And the blob.. Can't be killed anyways.

**Comment by DrFeederino** [comment]
Hey! Thanks for the suggestion, didn't get any notification but whatever.

Regarding the suggestion of yours, yeah, I can def see that it doesn't make total sense for the ghost girl. But regarding others, I def see it as "Enemy X steps on it and triggers it" kind of thing.

EDIT: as to when I can do it, I think I'll update it with the next version I have been cooking. Thanks for playing with my mod :)

**Comment by Diffle** [comment]
> Hey! Thanks for the suggestion, didn't get any notification but whatever.
> 
> Regarding the suggestion of yours, yeah, I can def see that it doesn't make total sense for the ghost girl. But regarding others, I def see it as "Enemy X steps on it and triggers it" kind of thing.
> 
> EDIT: as to when I can do it, I think I'll update it with the next version I have been cooking. Thanks for playing with my mod :)

Hahaha, I was actually kinda concerned if I even wrote in the right place. Thank you for creating this amazing mod; can't live without it now, haha. 

Also: in my opinion, you should change the icon on Thunderstore. It's very unremarkable, and it's very hard to guess what this mod even adds. I was browsing Thunderstore and did not notice your mod even though I knew its icon already.

**Comment by DrFeederino** [comment]
Oh yeah, the icon will definitely be reworked in the near future lol.

**Comment by DrFeederino** [comment]
Done it with [v1.6.0](https://github.com/DrFeederino/AndysModsPlugin/commit/9211c8b2fdd670d9f04811b936e761e6bdbef5f6#diff-506e4015b25864a5742e08791a791910a1af35a12bc2dcaae84c43ac0dec08b6R21), thank you again for the suggestion!
