### ISSUE TITLE
Better options to enable/disable mods

### ISSUE THREAD

**Issue by DoctorVolt** [DrFeederino/AndysModsPlugin#2]
It's very frustrating to know whether Lethal Turrets/Landmines are on or off. There's no documentation as to whether they're on or off by default, and no way to know in-game whether or not they're actually on, except by actually witnessing them in action. 

Two suggestions: 
1) All toggle commands, when used, should output whether you've just turned the corresponding setting on or off. 
2) Set up config settings that control what each mod is set to on startup, so if you don't need to change them on the fly, you can just set-and-forget. (I say "on startup" because I'm not sure if mods can modify their own config settings in-game. If so, it'd be even better if chat toggle commands just changed the config settings, so they act like variables you can modify both in-game through chat commands and out-of-game through the settings dialog.) 

I'd also like to make a separate plea to just mirror all of these into individual mods. I'm only here for Lethal Turrets and Lethal Landmines, and I'm sure there are other people just here for Bonk, or Quick Switch. You've got a great set of well-conceived, well-executed mods here (along with some cool WIP ideas), but I'm not interested in learning and using a separate in-game mod manager just for a couple of them. I'm still learning Thunderstore/r2modman, and I'd much rather be able to manage them there, like any other mod. 

Thank you!

**Comment by DrFeederino** [comment]
Hey!

First of all, thanks for playing my mod :)

Second, I agree I should have mentioned in the description that **by default all mods are enabled**. The feedback when turning off/on with command chat is def needed, but so far, I have to manage my own human resource what to do first. I laid out the foundation for the future:  I would love to have a menu with all mods listed, their toggles, all of it saved to the config file and loading it up. In the meantime, it is logged in the console which BepInEx creates and outputs everything to. It contains some useful debugging information and I do output current toggle state there too.

And similarly, I don't even see the point of releasing mods separately, this is too much of hassle for me and this is _my collection_ of them. If you would love to do it yourself, you definitely have my permission or perhaps do a PR here. This is MIT licensed repo, after all!

**Comment by DrFeederino** [comment]
[Release v1.8.0 addresses the issue. Tooltips appear when you toggle mod on/off and config file has been added.](https://github.com/DrFeederino/AndysModsPlugin/blob/253179104e986b966e4debbb36937d1647eb41f1/README.md?plain=1#L44)

@DoctorVolt  Let me know if you have any problems or further suggestions :)

**Comment by DrFeederino** [comment]
I'm closing the issue since no response was given and I did address the concern somewhat. If you have other issues, don't hesitate to open a new issue!
